<?php

$combos = array (
  'O:-)' => 'angel.gif',
  ':-)' => 'smile.gif',
  ':-(' => 'sad.gif',
  ';-)' => 'wink.gif',
  ':-P' => 'tongue.gif',
  '8-)' => 'dirol.gif',
  ':-D' => 'biggrin.gif',
  ':-[' => 'blush.gif',
  '=-O' => 'shok.gif',
  ':-*' => 'kiss2.gif',
  ':|(' => 'cray.gif',
  ':-X' => 'secret.gif',
  ']-o' => 'aggressive.gif',
  ':-|' => 'fool.gif',
  ':-/' => 'beee.gif',
  '*JOKINGLY*' => 'mosking.gif',
  ']:-]' => 'diablo.gif',
  '[:-}' => 'music2.gif',
  '*KISSED*' => 'air_kiss.gif',
  ':-!' => 'bad.gif',
  '*TIRED*' => 'boredom.gif',
  '*STOP*' => 'stop.gif',
  '*KISSING*' => 'kiss3.gif',
  '@}-]--' => 'give_rose.gif',
  '*THUMBS UP*' => 'good.gif',
  '*DRINK*' => 'drinks.gif',
  '*IN LOVE*' => 'heart.gif',
  '@=' => 'bomb.gif',
  '*HELP*' => 'help.gif',
  ']m[' => 'new_russian.gif',
  '%)' => 'wacko2.gif',
  '*OK*' => 'ok.gif',
  '*WASSUP*' => 'mamba.gif',
  '*SORRY*' => 'sorry.gif',
  '*BRAVO*' => 'clapping.gif',
  '*ROFL*' => 'rofl.gif',
  '*PARDON*' => 'pardon.gif',
  '*NO*' => 'nea.gif',
  '*CRAZY*' => 'crazy.gif',
  '*DONT_KNOW*' => 'unknw.gif',
  '*DANCE*' => 'dance4.gif',
  '*YAHOO*' => 'yahoo.gif',
  '*HI*' => 'preved.gif',
  '*BYE*' => 'bye.gif',
  '*YES*' => 'yes3.gif',
  ';D' => 'acute.gif',
  '*WALL*' => 'dash1.gif',
  '*WRITE*' => 'mail1.gif',
  '*SCRATCH*' => 'scratch_head.gif',
);
